# Generated by Django 5.0.6 on 2026-08-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_gender_user_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='telegram chat id'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='telegram link code'),
        ),
    ]
