# Generated by Django 5.0.6 on 2026-08-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_telegram_chat_id_user_telegram_link_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='phone'),
        ),
    ]
