# Generated by Django 5.0.6 on 2026-03-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberprofile',
            name='working_days_per_week',
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='is_open_now',
            field=models.BooleanField(default=False, verbose_name='is open now'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='work_days',
            field=models.CharField(default='Mon,Tue,Wed,Thu,Fri,Sat,Sun', max_length=100, verbose_name='work days'),
        ),
    ]
