# Generated by Django 5.0.6 on 2026-03-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_remove_barberprofile_working_days_per_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='shop_type',
            field=models.CharField(choices=[('men', "Men's Barber"), ('women', "Women's Salon"), ('unisex', 'Unisex')], default='men', max_length=20, verbose_name='shop type'),
        ),
    ]
