# Generated by Django 5.0.6 on 2026-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_remove_barberprofile_address_barberprofile_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
    ]
