# Generated by Django 5.0.6 on 2026-03-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_barberprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberprofile',
            name='shop_type',
            field=models.CharField(choices=[('men', "Men's Barber"), ('women', "Women's Salon")], default='men', max_length=20, verbose_name='shop type'),
        ),
    ]
