# Generated by Django 5.0.6 on 2026-03-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_barberprofile_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price'),
        ),
    ]
