# Generated by Django 5.0.6 on 2026-03-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_barberprofile_currency_service_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='bad_ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='good_ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='rating',
            field=models.FloatField(default=5.0, verbose_name='rating'),
        ),
    ]
