# Generated by Django 5.0.6 on 2026-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_barberprofile_bad_ratings_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberprofile',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='rating'),
        ),
    ]
