# Generated by Django 5.0.6 on 2026-03-28 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_alter_barberprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
