# Generated by Django 5.0.6 on 2026-08-12 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_barberprofile_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='claim_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, verbose_name='claim code'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='contact phone'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='is_claimed',
            field=models.BooleanField(default=True, verbose_name='claimed by owner'),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
