# Generated by Django 5.0.6 on 2026-03-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_notified',
            field=models.BooleanField(default=False),
        ),
    ]
