# Generated by Django 5.0.6 on 2026-03-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_appointment_client_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_cancel_reason',
            field=models.TextField(blank=True),
        ),
    ]
