# Generated by Django 5.0.6 on 2026-03-28 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_appointment_cancelled_at'),
        ('shops', '0006_barberprofile_currency_service_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='shops.employee'),
        ),
    ]
