# Generated by Django 5.0.6 on 2026-03-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_appointment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rating_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rating_is_good',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('no_show', 'Did Not Show')], default='pending', max_length=20),
        ),
    ]
